#!/bin/bash
# make sure unicorn is down
# 如果只是要重新加载数据结构，使用这个脚本；如果要删除data,public/s/files,public/s/theme等初始目录，使用bundle exec rake shopqi:bootstrap
bundle exec rake db:drop
bundle exec rake db:drop RAILS_ENV=test

bundle exec rake db:create
bundle exec rake db:create RAILS_ENV=test

bundle exec rake db:migrate
bundle exec rake db:schema:load RAILS_ENV=test

bundle exec rake resque:clear
bundle exec rake db:seed
